List French = [
  {
    "serves": "4",
    "prepTime": "2hrs",
    "cookTime": "2hrs",
    "asset": "assets/crepes.jpg",
    "name": "Crepes With Orange and Passionfruit Compote",
    "items": "8 passionfruit, halved\n1/3 cup (80ml) light agave syrup (see "
        "notes) or maple syrup\n1 cup (150g) plain flour, sifted\n2 eggs\n300ml milk"
        "\n50g butter, melted\n250g creme fraiche or sour cream\n1 teaspoon vanilla extract\n100g hazelnuts, roasted, crushed",
    "process": "1. To make the compote, place orange segments and juice in a "
        "saucepan. Scoop passionfruit pulp into a sieve set over the pan and press to extract juice. Discard seeds. Add 2 tablespoons agave syrup to the pan and bring to a simmer over medium heat. Using a slotted spoon, transfer orange segments to a bowl. Bring liquid to the boil, then simmer over medium-high heat for 5 mins or until reduced by half. Pour over the orange and set aside to cool.\n2. To make the crepes, combine flour and a pinch of salt in a large bowl. Make a well in the centre, add the eggs, then gradually add the milk, whisking until smooth – the consistency should be similar to very runny cream (add more milk if necessary). Alternatively, whiz in a food processor. Pour batter into a jug, cover and stand at room temperature for 20 mins.\n3. Preheat oven to 150°C. Place a 16cm crepe pan over medium heat and brush with a little melted butter. Pour in enough batter to almost coat the bottom of the pan, then swirl pan to completely coat. Cook for 1 minute, then flip and cook for a further 30 seconds or until golden. Transfer to a plate and keep warm in the oven. Repeat with remaining butter and batter to make 12 crepes.\n4. Place creme fraiche, vanilla and remaining 2 tablespoons agave syrup in a bowl and stir to combine.\n5. Place a dollop of creme fraiche and 3 orange segments on one-quarter of each crepe. Fold crepe in half to cover filling, then in half again to form a parcel. Repeat with remaining crepes and filling. Divide crepes among plates and top with remaining creme fraiche and compote. Scatter with hazelnuts, then serve."
  },
  {
    "serves": "6 to 8",
    "prepTime": "6-24hrs",
    "cookTime": "1 hrs",
    "asset": "assets/countries/casso.jpg",
    "name": "Traditional French Cassoulet Recipe",
    "items":
        "1 pound dried cannelloni beans\nKosher salt\n1 quart homemade or store-bought low-sodium chicken stock\n3 packets (3/4 ounces) unflavored gelatin, such as Knox (see note)\n2 tablespoons duck fat (optional)\n8 ounces salt pork, cut into 3/4-inch cubes\n6 to 8 pieces of chicken thighs and drumsticks, or 4 whole chicken leg quarters\nFreshly ground black pepper\n1 pound garlic sausage (2 to 4 links depending on size)\n1 large onion, finely diced (about 1 cup)\n1 carrot, unpeeled, cut into 3-inch sections\n2 stalks celery, cut into 3-inch sections\n1 whole head garlic\n4 sprigs parsley\n2 bay leaves\n6 cloves",
    "process":
        "1.\nIn a large bowl, cover beans with 3 quarts water and add 3 tablespoons salt. Stir to combine and let sit at room temperature overnight. Drain and rinse beans and set aside.\n2.\nAdjust oven rack to lower middle position and preheat oven to 300°F. Place stock in a large liquid measuring cup and sprinkle gelatin over the top. Set aside. Heat duck fat (if using) in a large Dutch oven over high heat until shimmering. Add salt pork and cook, stirring occasionally, until browned all over, about 8 mins. Transfer to a large bowl and set aside. (If not using duck fat, cook pork with no additional fat.)\n3.\nSeason chicken pieces with pepper (do not add salt) and place skin side-down in now-empty pan. Cook without moving until well browned, 6 to 8 mins. Flip chicken pieces and continue cooking until lightly browned on second side, about 3 mins longer. Transfer to bowl with salt pork.\n4.\nAdd sausages and cook, turning occasionally, until well-browned on both sides. Transfer to bowl with salt pork and chicken. Drain all but 2 tablespoons fat from pot.\n5.\nAdd onions to pot and cook, stirring and scraping up browned bits from the bottom of the pot. Cook until onions are translucent but not browned, about 4 mins. Add drained beans, carrot, celery, garlic, parsley, bay leaves, cloves, and stock/gelatin mixture. Bring to a simmer over high heat. Reduce to low, cover Dutch oven and cook until beans are almost tender but retain a slight bite, about 45 mins.\n6.\nUsing tongs, remove carrots, celery, parsley, bay leaves, and cloves and discard. Add meats to pot and stir to incorporate, making sure that the chicken pieces end up on top of the beans with the skin facing upwards. Beans should be almost completely submerged. Transfer to oven and cook, uncovered, until a thin crust forms on top, about 2 hrs, adding more water by pouring it carefully down the side of the pot as necessary to keep beans mostly covered.\n7.\nBreak crust with a spoon and shake pot gently to redistribute. Return to oven and continue cooking, stopping to break and shake the crust every 30 mins until you reach the 4 1/2 hrs mark. Return to oven and continue cooking undisturbed until the crust is deep brown and thick, about 5 to 6 hrs total. Serve immediately."
  },
  {
    "serves": "6",
    "prepTime": "3hr 30min",
    "cookTime": "1hr 30min",
    "asset": "assets/countries/boeuf.jpg",
    "name":
        "Boeuf Bourguignon (Beef Stew With Red Wine, Mushrooms, and Bacon) Recipe",
    "items":
        "2 cups (500ml) homemade chicken stock or store-bought low-sodium broth (see note)\n4 packets unflavored powdered gelatin (3 tablespoons plus 1 teaspoon; 30g) (see note)\n2 tablespoons (30ml) vegetable oil, plus more as needed\n3 pounds (1.25kg) whole boneless beef chuck roast, cut into 3 steaks\nKosher salt and freshly ground black pepper\n1 1/4 pounds carrots (600g; about 3 large), 1/2 pound (250g) peeled and split lengthwise, 3/4 pound (350g) cut into large dice (about 1 1/2 cups)\n1/2 pound yellow onions (250g; about 2 medium), peeled and split in half through the root\n4 medium cloves garlic, lightly crushed\n1/4 cup (60ml) cognac or brandy (optional)\n3 cups (750ml) dry red wine\n1 tablespoon (15ml) Asian fish sauce\n1 tablespoon (15ml) soy sauce\n1 bouquet garnis (about 4 sprigs thyme, 3 sprigs parsley, and 1 bay leaf, tied together with kitchen twine)\n2 tablespoons (20g) all-purpose flour\n1/4 pound (110g) slab bacon or salt pork, cut into 1- by 1/4- by 1/4-inch sticks (see note)\n1 pound cremini mushrooms (450g), woody stems trimmed if necessary and caps quartered\n8 ounces white and/or red pearl onions (225g), peeled\nMinced flat-leaf parsley leaves and tender stems, for garnish",
    "process":
        "1.\nPreheat oven to 300°F. Pour chicken stock into a medium bowl and sprinkle gelatin evenly all over surface, allowing each packet's worth of gelatin to soak up stock before sprinkling next one on. Set aside.\n2.\nIn a large Dutch oven, heat oil over medium-high heat until shimmering. Season beef all over with salt and pepper and add to Dutch oven. Cook, turning occasionally, until beef is well browned on 2 sides, about 10 mins. Transfer beef to a rimmed baking sheet.\n3.\nAdd split carrots, halved onions, and garlic to Dutch oven and cook, turning occasionally, until lightly browned, about 4 mins; lower heat if browned bits on bottom of Dutch oven threaten to burn.\n4.\nAdd brandy, if using, and boil until alcohol has nearly cooked off, about 2 mins. (If not using brandy, proceed with next step.)\n5.\nScrape chicken stock and all gelatin into Dutch oven. Add red wine, fish sauce, soy sauce, and bouquet garnis and bring to a simmer, then lower heat to maintain simmer. Meanwhile, cut beef into 2-inch chunks and transfer to a large mixing bowl. Add flour and stir until beef is evenly coated in a floury paste. Add beef and any accumulated juices to Dutch oven. Transfer to oven, cover with lid partially open, and cook until beef is starting to become tender, about 1 hrs 30 mins.\n6.\nMeanwhile, in a large skillet, cook lardons over medium-high heat, stirring occasionally, until fat has rendered and lardons are lightly browned and crisp, about 6 mins. Transfer lardons to a plate with a slotted spoon.\n7.\nAdd mushrooms to skillet and cook, stirring occasionally, until mushrooms have released their liquid and browned, about 12 mins; add oil as needed if pan becomes too dry. Add diced carrots and pearl onions and continue to cook, stirring occasionally, until lightly browned, about 5 mins.\n8.\nRemove stew from oven. Using tongs, fish out and discard large pieces of carrot and onion. Discard bouquet garnis. Using a ladle, skim off and discard accumulated fat on surface. Add reserved lardons and sautéed carrots, onions, and mushrooms to stew, return to oven, and continue to cook, uncovered, until beef is tender, about 30 mins longer.\n9.\nRemove stew from oven. If serving right away, skim off any additional fat from surface. Season with salt and pepper, if needed. Allow to cool slightly before serving, then serve topped with parsley. If making ahead, cool down stew, then chill in refrigerator; remove solid fat cap from surface once fully chilled. Reheat stew on the stovetop or in a low oven."
  },
  {
    "serves": "Makes eight 4-ounce soufflés",
    "prepTime": "1 hrs",
    "cookTime": "45 mins",
    "asset": "assets/countries/souffle..jpeg",
    "name": "Chocolate soufflé",
    "items":
        "For the Ramekins:\nSoftened unsalted butter, for greasing the ramekins (approximately 3 tablespoons)\nGranulated sugar, for coating ramekins (approximately 3 tablespoons)\nFor the Soufflés:\n2 1/2 ounces (about 1/4 cup; 70g) heavy cream and/or whole milk\n1 3/4 ounces 68-71% dark chocolate, chopped (about 1/3 cup; 50g)\n1 3/4 ounces unsweetened chocolate, chopped (about 1/3 cup; 50g)\n1 3/4 ounces (1/2 cup; 50g) Dutch process cocoa powder\n3 1/2 ounces (scant 1/2 cup; 100g) water\n1 teaspoon vanilla extract\nWhites from 8 large eggs, straight from the fridge (8 3/4 ounces; 250g)\n3 1/2 ounces (1/2 cup; 100g) granulated sugar\n3/4 teaspoon Diamond Crystal kosher salt; for table salt, use half as much by volume",
    "process":
        "1.\nPreheat oven to 400°F (204°C) with the convection fan turned off and oven rack in center position. Liberally butter the interiors of eight 4-ounce ramekins, making sure to butter right up to the upper edge of the rim of each ramekin. Sugar the buttered insides evenly, tapping out excess, and set ramekins aside.\n2.\nPlace 2 1/2 cups water in a 3-quart sauce pan on the stove over medium heat. In a large, heat-proof bowl that will sit comfortably on the pot without toppling over or touching the water below, combine cream and/or milk, dark chocolate, and unsweetened chocolate. Whisk gently until chocolate is melted, cream and/or milk are fully incorporated, and a smooth ganache has formed.\n3.\nTurn off heat, then carefully whisk in cocoa powder, water, and vanilla extract until smooth. Leave bowl atop pot of hot water, off the heat, to keep the ganache warm.\n4.\nIn the bowl of a stand mixer fitted with the whisk attachment, beat egg whites on high speed until they become foamy, about 20 seconds. Reduce mixer speed to medium and gradually add sugar and salt, then return to high speed and whisk the egg white mixture until firm, glossy, smooth peaks form, about 2 mins.\n5.\nUsing a silicone spatula, stir about 1/4 of the egg whites into the chocolate ganache until thoroughly incorporated, to lighten it. Then gently but thoroughly fold in the remaining egg whites, taking care not to deflate the mixture, until no visible whites remain. As soon as there are no more unincorporated whites, spoon soufflé mixture into prepared ramekins just to the top, then even the tops with an offset spatula. (You may prepare soufflés up to this point, and bake later; see note.)\n6.\nEvenly space ramekins on a rimmed half-sheet tray and bake in the center of the oven for 12 mins for soufflés that are wet on the inside, or 13 to 14 mins for ones that are drier. The soufflés will have risen tall above the rims of the ramekins and look dry on top. Serve immediately."
  },
  {
    "serves": "2",
    "prepTime": "25mins",
    "cookTime": "5mins",
    "asset": "assets/countries/flam.jpg",
    "name": "Flamiche",
    "items":
        "1 frozen pie crust\n3 cup leek\n1 egg\nblack pepper as required\n1 tablespoon butter\n1/2 cup low fat milk\nsalt as required",
    "process":
        "Step 1\nTo make this snack recipe, preheat the oven to 200 degrees Celsius. On a chopping board, thinly slice the leeks and add these to a bowl. Place a pan over medium flame and melt butter in it. When the butter has melted, add the thinly sliced leeks to it and mix them well. Saute these for a while and let them get tender. once done, take it off the flame.\nStep 2\nNow, crack open the eggs in a bowl and beat them. Add the milk in the bowl containing the eggs and season with salt and black pepper powder. Now, add the fried leeks to this bowl and whisk it well. Now, place the pie crust in a baking dish and add the egg-leek mixture to it. Spread it evenly.\nStep 3\nPlace the baking dish in the preheated oven and bake the Flamiche for 10 to 15 mins. Reduce the temperature post that to 170 degrees Celsius and bake it until it is lightly brown in color on the top. Once bakes, take it out from the oven and place it on a plate. Slice and serve it warm to enjoy!"
  },
  {
    "serves": "4",
    "prepTime": "4+24hrs",
    "cookTime": "20 mins",
    "asset": "assets/countries/confit.jpg",
    "name": " Confit de canard",
    "items":
        "4 duck legs (about 2 1/4 pounds total; 1kg) (see note)\n1 tablespoon plus 1 teaspoon (16g) Diamond Crystal kosher salt; ; for table salt, use about half as much by volume or the same weight\n6 large shallots (12 ounces; 340g), quartered\n1 small onion (4 ounces; 110g), cut into 2-inch pieces (see note)\n6 medium cloves garlic (30g)\n1/2 bunch (2 ounces; 55g) flat-leaf parsley leaves and tender stems, roughly chopped\n10 sprigs fresh thyme\n2 teaspoons (6g) whole black peppercorns\n2 to 4 cups (475 to 950ml) rendered duck fat ",
    "process":
        "1.\nThe Day Before Cooking Confit: Season duck legs evenly on all sides with salt; set aside. Combine shallots, onion, garlic, and parsley in food processor bowl and pulse until finely chopped but not puréed, about 15 pulses.\n2.\nTransfer half the vegetable mixture to a nonreactive container that can fit duck legs snugly, such as a baking dish, and spread in an even layer. Scatter half the thyme sprigs and peppercorns over vegetable mixture, then arrange duck legs skin-side up in an even layer on top, pressing them into vegetable mixture. Distribute remaining thyme sprigs and peppercorns over duck legs, followed by the vegetable mixture, spreading it evenly so legs are well-coated. Cover tightly with plastic wrap and refrigerate for at least 24 hrs and up to 48 hrs.\nAlternatively, combine duck legs, vegetable mixture, thyme, and peppercorns in a 1-gallon zipper-lock bag. Seal bag, pressing out as much air as possible. Massage bag until duck legs are evenly coated on all sides. Lay bag flat on rimmed baking sheet and refrigerate for at least 24 hrs and up to 48 hrs.\n3.\nWhen Ready to Cook: Adjust oven rack to middle position and preheat oven to 225°F (105°C). Melt duck fat, either in 3-quart saucier over low heat or in a microwave-safe bowl in the microwave. Remove duck legs from cure, wiping away as much of the cure mixture as possible before rinsing legs gently under cold water to remove all seasonings; discard cure. Pat duck legs dry with paper towels, then arrange in single layer in saucier with duck fat (if using), making sure they are completely submerged in fat. Alternatively, arrange duck legs snugly in a small baking dish and cover with melted duck fat, making sure legs are fully submerged in fat.\n4.\nCover saucier or baking dish with lid or aluminum foil, and transfer to oven. Cook until duck is completely tender and meat shows almost no resistance when pierced with a paring knife, and skin has begun to pull away from bottom of the drumstick, 3 1/2 to 4 hrs.\n5.\nRemove from oven and cool duck to room temperature in its cooking vessel, removing lid but keeping it submerged in fat. Once cool, cover container tightly and transfer to refrigerator, where confit can be stored for up to 1 month."
  },
  {
    "serves": "4",
    "prepTime": "40min",
    "cookTime": "30min",
    "asset": "assets/countries/salade-nicoise.jpg",
    "name": "Salade Niçoise",
    "items":
        "1/4 cup cider vinegar\n2 tablespoons olive oil\n1/2 teaspoon Dijon mustard\n2 sprigs of thyme, leaves picked off\nKosher salt and cracked black pepper\n8 ounces mixed greens\n4 eggs, hard-boiled\n4 small Yukon gold potatoes, boiled and chilled\n1/3 pound green beans, washed, blanched and chilled\n8 anchovies\n2 (6.5 ounce) cans good qualtiy tuna\na small handful nicoise style olives",
    "process":
        "1.\nWhisk cider vinegar, olive oil, mustard and thyme together and season to taste with salt and pepper.\n2.\nSlice hard-boiled eggs in half; quarter potatoes and tomatoes. Dress greens and place in large salad bowl. Dress potatoes, tomatoes and green beans in remaining dressing and place on salad. Top each halved egg with an anchovy and place on salad, followed by a small handful of olives. Place canned tuna on any remaining area of salad, or mound it in the middle, and drizzle with any remaining dressing. Sprinkle entire salad with some salt and pepper, and serve with plenty of white wine and crusty bread."
  },
  {
    "serves": "2 quarts",
    "prepTime": "2 hrs",
    "cookTime": "1hr 30min",
    "asset": "assets/countries/rata.jpg",
    "name": "Provençal Ratatouille Recipe",
    "items":
        "3 cups 1/4-inch diced summer squash, such as zucchini and yellow squash (about 4 small or 2 medium squash)\n3 cups 1/4-inch diced Italian eggplant (about 1 medium eggplant)\nKosher salt and freshly ground black pepper\n3/4 cup (12 tablespoons) extra-virgin olive oil, divided, plus more as needed\n3 cups 1/4-inch diced yellow onion (about 3 medium onions)\n6 medium cloves garlic, minced (about 2 tablespoons)\n3 cups 1/4-inch diced red and yellow bell pepper (about 4 large peppers)\n2 cups pureed canned whole tomatoes, with their juices, from 1 (28-ounce) can (see note)\n1 bouquet garni (herb bundle), made from fresh herbs such as thyme, parsley, and basil, tied together with butcher's twine (see note)\nChopped fresh parsley leaves and tender stems, for garnish (optional)",
    "process":
        "1.\nPlace summer squash in a wire mesh strainer set over a bowl; place eggplant in a second wire mesh strainer and set over a second bowl. Toss both with a liberal amount of kosher salt and let stand to drain at least 15 mins and up to 1 hrs. Discard any liquid that collects in the bowls.\n2.\nIn a large skillet, heat 3 tablespoons olive oil over medium-high heat until shimmering. Add onion and garlic, season with salt, and cook, stirring, until softened, about 6 mins. Scrape onion and garlic onto a rimmed baking sheet and spread in an even layer to cool for 3 mins. Transfer onion and garlic to a large pot.\n3.\nMeanwhile, add 3 more tablespoons olive oil to skillet and heat over medium-high heat until shimmering. Add bell pepper, season with salt, and cook, stirring, until softened, about 7 mins. Scrape bell pepper onto the rimmed baking sheet in an even layer to cool for 3 mins. Transfer bell pepper to pot with onion.\n4.\nAdd 3 more tablespoons olive oil to skillet and heat over medium-high heat until shimmering. Add summer squash and cook, stirring, until softened, about 4 mins. Scrape onto rimmed baking sheet in an even layer to cool for 3 mins. Transfer to pot with onion and bell pepper.\n5.\nAdd remaining 3 tablespoons olive oil to skillet and heat over medium-high heat until shimmering. Add eggplant and cook, stirring, until softened, about 4 mins; add more olive oil as needed if skillet dries out while cooking eggplant. Scrape eggplant into pot with other vegetables and stir to combine.\n6.\nSet pot of vegetables over medium-high heat and stir in tomato puree and herb bundle; heat until ratatouille is gently bubbling, then lower heat to medium and cook, stirring, until tomato puree coats vegetables in a thick sauce, about 15 mins. Discard herb bundle. Season with salt, stir in chopped parsley (if using), and drizzle with a small amount of fresh extra-virgin olive oil. Serve right away, or chill and serve either reheated, slightly chilled, or at room temperature."
  },
  {
    "serves": "8",
    "prepTime": "3 hrs",
    "cookTime": "1 hrs",
    "asset": "assets/countries/tartetatin.jpeg",
    "name": "Tarte Tatin Recipe",
    "items":
        "14 ounces (about 1 package) puff pastry dough, cold (see note)\nFlour, for dusting\n4 tablespoons unsalted butter\n1/2 cup plus 1 tablespoon (about 4 ounces) granulated sugar\n30 ounces peeled and cored apples and or pears, cut in half down the axis (about 10 medium)\n6 tablespoons apple cider\n1 pinch of salt",
    "process":
        "1.\nOn a bench dusted with flour, roll out the puff pastry until it is just shy of 1/4 inch thick and completely covers the circumference of the 12-inch skillet that you will use for baking the tart tatin, ensuring that there is at least 1 inch of overhang all around the edge of the pan. Place the sheet of puff pastry on a parchment lined sheet tray in the fridge to relax for 30 mins or more.\n2.\nPosition the rack in the center of the oven and preheat the oven to 400°F. Place the frying pan over medium heat. Melt the butter in the pan, tilting it to evenly coat the bottom. Sprinkle the sugar over the butter and tilt the pan to evenly disperse the sugar. When the sugar just begins to melt and brown slightly, place the fruit in the pan. Saute the fruit on each side for two mins, taking care not to dent the fruit on the round side that will face up in the final tart. The fruit should only be slightly cooked. Add the cider to deglaze the pan and position the fruit around the pan, packed tightly together, with the cut side facing up. Remove the pan from heat. Cover the top of the apples with the chilled pastry and tuck all of the overhanging dough down along the inside of the pan, so it creates a crust around the apples. Place the pan in the oven and bake for 20 mins at 400°F, then reduce the temperature to 350°F and bake until the crust is a deep golden brown and very firm to the touch with the juices bubbling vigorously beneath the crust, about 20 mins longer. Remove the tart from the oven and allow it to sit for one minute.\n3.\nUsing oven mitts or kitchen towels, place an inverted plate of greater size than the pan over the top of the tart. Grasp the plate and hold it firmly against the pan. Working swiftly, invert the pan so that the plate is on the bottom and the tart is flipped with the fruit on top. Remove the pan and take caution, the juices from the fruit will be very hot. Allow them to drip out of the pan and onto the tart. Allow the tart to cool for 10 mins before serving warm, or place in the oven for 5 mins before serving."
  }
];
